---

- name: change the user to run httpd as
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - regexp: "User apache"
      line: "User keystone"
    - regexp: "Group apache"
      line: "Group keystone"
  notify:
    - Restart webserver

- name: WSGI Tell apache to use the hostname as the servername
  lineinfile:
    dest: '{{ openstack_keystone_webserver_conf_path }}'
    line: 'ServerName {{ openstack_keystone_hostname }}'
  notify:
    - Restart webserver

- name: WSGI Create the WSGI Keystone configuration file
  template:
    src: 'wsgi-keystone.conf'
    dest: '{{ openstack_keystone_webserver_new_conf_dir_path }}/wsgi-keystone.conf'
  notify:
    - Restart webserver

- name: WSGI Enable the identity service virtual hosts
  file:
    src: '/etc/apache2/sites-available/{{ item.name }}'
    dest: '/etc/apache2/sites-enabled/{{ item.name }}'
    state: link
  notify:
    - Restart webserver
  when: ansible_os_family == 'Debian'
  with_items:
    - name: 'wsgi-keystone.conf'
